# Generated by Django 4.0.4 on 2022-06-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listwatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listwatchlist', to='auctions.listing')),
                ('userwatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
