# Generated by Django 4.0.4 on 2022-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_bid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('user', 'list'), name='one_bid'),
        ),
    ]
