# Generated by Django 4.0.4 on 2022-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_one_bid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='one_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='open_or_close',
            field=models.BooleanField(default=True),
        ),
    ]
