# Generated by Django 4.0.4 on 2022-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments_comment_comments_date_comments_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, default='nothing', max_length=200),
        ),
    ]
