# Generated by Django 4.0.4 on 2022-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
