# Generated by Django 4.0.4 on 2022-06-16 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_newpost_like_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedpost', to='network.newpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
